## Basic Configuration
baseURL = "https://aslamplr.github.io/"
languageCode = "en-us"

title = "Infinite Study"
theme = "hyde-hyde"

## Site Settings
[params]
    author = "Aslam Ahammed"
    title = "Infinite Study"
    description = "My (deep) dive into Deep learning, Re-inforcement learning, and AI, and other stuffs!"
    authorimage = "/img/logo.png"
    dateformat = "Monday, Jan 2, 2006"

    # sidebar, copyright & licence
    copyright = "@aslamplr"
    licence = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    highlightjs = true
    hughlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "aslamplr"
    twitter = "aslamplr"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 300
    url = "/about/"
