on: push
name: Build and deploy on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: zola-deploy-step
      uses: aslamplr/zola-deploy-action@master
      env:
        DEPLOYMENT_REPOSITORY: aslamplr/aslamplr.github.io
        PAGES_BRANCH: master 
        TOKEN: ${{ secrets.TOKEN }}
        DRAFTS_OUTPUT_DIR: public/drafts
        DRAFTS_BASE_URL: https://aslamplr.github.io/drafts
